name: macOS latest

on: [ push, pull_request ]

jobs:
  Python_37:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Install Python 3.7
        run: |
          brew install python@3.7
      - name: Install dependencies
        run: |
          brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf pkg-config
          python3 -m pip install setuptools -U
          python3 -m pip install pygame-ce
          python3 -m pip install .
      - name: Run Tests
        run: python3 -m unittest

  Python_38:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Install Python 3.8
        run: |
          brew install python@3.8
      - name: Install dependencies
        run: |
          brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf pkg-config
          python3 -m pip install setuptools -U
          python3 -m pip install pygame-ce
          python3 -m pip install .
      - name: Run Tests
        run: python3 -m unittest

  Python_39:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Install Python 3.9
        run: |
          brew install python@3.9
      - name: Install dependencies
        run: |
          brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf pkg-config
          python3 -m pip install setuptools -U
          python3 -m pip install pygame-ce
          python3 -m pip install .
      - name: Run Tests
        run: python3 -m unittest

  Python_310:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Install Python 3.10
        run: |
          brew install python@3.10
      - name: Install dependencies
        run: |
          brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf pkg-config
          python3 -m pip install setuptools -U
          python3 -m pip install pygame-ce
          python3 -m pip install .
      - name: Run Tests
        run: python3 -m unittest

  Python_311:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Install Python 3.11
        run: |
          brew install python@3.11
      - name: Install dependencies
        run: |
          brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf pkg-config
          python3 -m pip install setuptools -U
          python3 -m pip install pygame-ce
          python3 -m pip install .
      - name: Run Tests
        run: python3 -m unittest
