name: Windows latest

on: [ push, pull_request ]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10-dev, 3.11]
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Install packages
        run: |
          py -${{ matrix.python-version }} -m pip install --upgrade pip
          py -${{ matrix.python-version }} -m pip install pygame-ce
          py -${{ matrix.python-version }} -m pip install .
      - name: Run Tests
        run: py -${{ matrix.python-version }} -m unittest